name: saferun
description: "SafeRun App — Flutter + Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI e gerenciamento de estado
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Firebase (todas compatíveis com firebase_core 3.x)
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.5
  firebase_analytics: ^11.6.0

  # GPS e mapas
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  app_settings: ^5.1.1
  shared_preferences: ^2.3.2
  reorderables: ^0.6.0
  intl: ^0.20.2

  # ⚙️ Extras do app
  vibration: ^3.1.4
  flutter_tts: ^3.8.0
  share_plus: ^10.0.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar_placeholder.png
